BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE COMPRA CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE CANCION CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE USUARIO_FINAL CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE ADMINISTRADOR CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE RECARGA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ADMINISTRADOR';
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIO_FINAL';
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CANCION';
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COMPRA';
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RECARGA';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE ADMINISTRADOR (
  ID            NUMBER PRIMARY KEY,
  CORREO        VARCHAR2(120) NOT NULL UNIQUE,
  NOMBRE_USUARIO VARCHAR2(50) NOT NULL UNIQUE,
  CONSTRASENA   VARCHAR2(120) NOT NULL
);

CREATE TABLE USUARIO_FINAL (
  ID             NUMBER PRIMARY KEY,
  NOMBRE_COMPLETO VARCHAR2(120) NOT NULL,
  FECHA_NAC      DATE NOT NULL,
  NACIONALIDAD   VARCHAR2(60) NOT NULL,
  IDENTIFICACION VARCHAR2(40) NOT NULL UNIQUE,
  AVATAR         VARCHAR2(255),
  CORREO         VARCHAR2(120) NOT NULL UNIQUE,
  NOMBRE_USUARIO VARCHAR2(50) NOT NULL UNIQUE,
  CONSTRASENA    VARCHAR2(120) NOT NULL,
  SALDO          NUMBER(10,2) DEFAULT 0 NOT NULL
);

CREATE TABLE CANCION (
  ID             NUMBER PRIMARY KEY,
  NOMBRE         VARCHAR2(200) NOT NULL,
  ARTISTA        VARCHAR2(120) NOT NULL,
  ALBUM          VARCHAR2(120),
  COMPOSITOR     VARCHAR2(120),
  PRECIO         NUMBER(10,2) NOT NULL
);

CREATE TABLE COMPRA (
  ID          NUMBER PRIMARY KEY,
  USUARIO_ID  NUMBER NOT NULL REFERENCES USUARIO_FINAL(ID),
  CANCION_ID  NUMBER NOT NULL REFERENCES CANCION(ID),
  FECHA_COMPRA DATE DEFAULT SYSDATE NOT NULL,
  UNIQUE (USUARIO_ID, CANCION_ID)
);

CREATE TABLE RECARGA (
  ID          NUMBER PRIMARY KEY,
  USUARIO_ID  NUMBER NOT NULL REFERENCES USUARIO_FINAL(ID),
  MONTO       NUMBER(10,2) NOT NULL,
  FECHA_REC   DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_ADMINISTRADOR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USUARIO_FINAL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CANCION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COMPRA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RECARGA START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_ADMINISTRADOR_PK
BEFORE INSERT ON ADMINISTRADOR
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT SEQ_ADMINISTRADOR.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER TRG_USUARIO_FINAL_PK
BEFORE INSERT ON USUARIO_FINAL
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT SEQ_USUARIO_FINAL.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER TRG_CANCION_PK
BEFORE INSERT ON CANCION
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT SEQ_CANCION.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER TRG_COMPRA_PK
BEFORE INSERT ON COMPRA
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT SEQ_COMPRA.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER TRG_RECARGA_PK
BEFORE INSERT ON RECARGA
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT SEQ_RECARGA.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
