-- name: admin.buscarPorUsuario
SELECT ID, CORREO, NOMBRE_USUARIO, CONSTRASENA
FROM ADMINISTRADOR
WHERE NOMBRE_USUARIO = ?
-- name: admin.insert
INSERT INTO ADMINISTRADOR (ID, CORREO, NOMBRE_USUARIO, CONSTRASENA)
VALUES (SEQ_ADMINISTRADOR.NEXTVAL, ?, ?, ?)
-- name: admin.exists
SELECT CASE WHEN COUNT(*)>0 THEN 1 ELSE 0 END AS EXISTE FROM ADMINISTRADOR