-- name: cancion.insert
INSERT INTO CANCION (ID, NOMBRE, ARTISTA, ALBUM, PRECIO)
VALUES (SEQ_CANCION.NEXTVAL, ?, ?, ?, ?)

-- name: cancion.update
UPDATE CANCION
SET NOMBRE = ?,
    ARTISTA = ?,
    ALBUM = ?,
    PRECIO = ?
WHERE ID = ?

-- name: cancion.delete
DELETE FROM CANCION WHERE ID = ?

-- name: cancion.findById
SELECT ID, NOMBRE, ARTISTA, ALBUM, PRECIO
FROM CANCION
WHERE ID = ?

-- name: cancion.findAll
SELECT ID, NOMBRE, ARTISTA, ALBUM, PRECIO
FROM CANCION
ORDER BY NOMBRE

-- name: cancion.buscarPorNombre
SELECT ID, NOMBRE, ARTISTA, ALBUM, PRECIO
FROM CANCION
WHERE UPPER(NOMBRE) LIKE UPPER(?)
ORDER BY NOMBRE

-- name: cancion.buscarPorArtista
SELECT ID, NOMBRE, ARTISTA, ALBUM, PRECIO
FROM CANCION
WHERE UPPER(ARTISTA) LIKE UPPER(?)
ORDER BY NOMBRE

-- name: cancion.search
SELECT ID, NOMBRE, ARTISTA, ALBUM, PRECIO
FROM CANCION
WHERE (UPPER(NOMBRE) LIKE UPPER(?)
   OR  UPPER(ARTISTA) LIKE UPPER(?)
   OR  UPPER(ALBUM) LIKE UPPER(?))
ORDER BY NOMBRE
