-- name: compra.insert
INSERT INTO COMPRA (ID, USUARIO_ID, CANCION_ID, FECHA_COMPRA)
VALUES (SEQ_COMPRA.NEXTVAL, ?, ?, SYSDATE)
-- name: compra.yaComprada
SELECT CASE WHEN COUNT(*)>0 THEN 1 ELSE 0 END AS EXISTE
FROM COMPRA
WHERE USUARIO_ID = ? AND CANCION_ID = ?
-- name: compra.cancionesCompradas
SELECT c.ID, c.NOMBRE, c.ARTISTA, c.ALBUM, c.PRECIO FROM COMPRA cp
JOIN CANCION c ON c.ID = cp.CANCION_ID
WHERE cp.USUARIO_ID = ?
ORDER BY c.NOMBRE